Repository GakutoTobinaga/EitaTraining, pull requests merged in 2024-07, with the labels that each got.

#2 移植しました
  script.js
Labels: enhancement, Review effort [1-5]: 2

#6 関数の名前を修正
  script.js
Labels: Bug fix, Review effort [1-5]: 1

#9 BMI計算関数を追加
  script.js
Labels: enhancement, Review effort [1-5]: 2

#11 分類関数を追加しました
  script.js
Labels: enhancement, Review effort [1-5]: 2

#12 飲み物関数を作成しました
  function.js
Labels: enhancement, Review effort [1-5]: 2

#14 jsdocを直しました
  function.js
  script.js
Labels: documentation, Review effort [1-5]: 1

#22 ファイルを作成しました
  eita/function.js
  eita/index.html
  eita/script.js
  index.html
  script.js
Labels: enhancement, other, Review effort [1-5]: 3

#24 beveragesオブジェクトを追加しました。
  eita/function.js
Labels: enhancement, Review effort [1-5]: 2

#28 変更不可能にしました
  eita/function.js
Labels: enhancement, Review effort [1-5]: 2
